name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9.7'
  semgrep:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      
      - name: Create reports directory
        run: mkdir -p reports
      
      - name: Semgrep Security Scan with Autofix
        run: |
          semgrep scan \
            --config "p/python" \
            --config "p/secrets" \
            --config "p/owasp-top-ten" \
            --output reports/semgrep-results.sarif \
            --sarif \
            --autofix || true
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/semgrep-results.sarif
          
      - name: Upload Semgrep Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: reports/semgrep-results.sarif
          retention-days: 14
          
      - name: Create Pull Request with fixes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: 'fix: auto-fixes from semgrep'
          title: 'Semgrep Auto-fixes'
          body: |
            Автоматические исправления от Semgrep security scan
            
            Этот PR содержит автоматические исправления проблем безопасности, найденных Semgrep.
            Пожалуйста, проверьте изменения перед merge.
          branch: semgrep-fixes
          base: main
          delete-branch: true

          
  zap_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run App
        run: |
          python dsvpwa.py >> app.log &
          echo "Waiting for start..."
          sleep 20
          curl -v http://localhost:65413/ || true

      - name: Prepare ZAP Environment
        run: |
          sudo mkdir -p /zap/wrk
          sudo chown -R $USER:$USER /zap
          sudo chmod -R 755 /zap

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:65413/'
          cmd_options: '-I'
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false
          fail_action: false

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-logs
          path: app.log
          retention-days: 5

      - name: Upload ZAP Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: |
            zap-*
            *.html
          retention-days: 5
